package sips.cn.contract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-26T15:51:35.386+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "urn:sips:cn:contract", name = "PaymentService")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentService {

    @WebMethod
    @RequestWrapper(localName = "processPaymentWebInit", targetNamespace = "urn:sips:cn:contract", className = "sips.cn.contract.ProcessPaymentWebInit")
    @ResponseWrapper(localName = "processPaymentWebInitResponse", targetNamespace = "urn:sips:cn:contract", className = "sips.cn.contract.ProcessPaymentWebInitResponse")
    @WebResult(name = "output", targetNamespace = "urn:sips:cn:contract")
    public sips.cn.contract.PaymentWebInitOutput processPaymentWebInit(
            @WebParam(name = "input", targetNamespace = "urn:sips:cn:contract")
            sips.cn.contract.PaymentWebInitInput input
    );

    @WebMethod
    @RequestWrapper(localName = "processWalletManagementInit", targetNamespace = "urn:sips:cn:contract", className = "sips.cn.contract.ProcessWalletManagementInit")
    @ResponseWrapper(localName = "processWalletManagementInitResponse", targetNamespace = "urn:sips:cn:contract", className = "sips.cn.contract.ProcessWalletManagementInitResponse")
    @WebResult(name = "output", targetNamespace = "urn:sips:cn:contract")
    public sips.cn.contract.WalletManagementInitOutput processWalletManagementInit(
            @WebParam(name = "input", targetNamespace = "urn:sips:cn:contract")
            sips.cn.contract.WalletManagementInitInput input
    );
}
