package sips.en.contract.dvla;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-24T10:47:25.607+01:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "NotificationService", 
                  wsdlLocation = "/META-INF/IS011_v1f_NotificationService.wsdl",
                  targetNamespace = "urn:sips:en:contract:dvla") 
public class NotificationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sips:en:contract:dvla", "NotificationService");
    public final static QName NotificationImplPort = new QName("urn:sips:en:contract:dvla", "NotificationImplPort");
    static {
        URL url = NotificationService.class.getResource("/META-INF/IS011_v1f_NotificationService.wsdl");
        if (url == null) {
            url = NotificationService.class.getClassLoader().getResource("/META-INF/IS011_v1f_NotificationService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(NotificationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/META-INF/IS011_v1f_NotificationService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public NotificationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotificationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotificationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotificationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Notification
     */
    @WebEndpoint(name = "NotificationImplPort")
    public Notification getNotificationImplPort() {
        return super.getPort(NotificationImplPort, Notification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Notification
     */
    @WebEndpoint(name = "NotificationImplPort")
    public Notification getNotificationImplPort(WebServiceFeature... features) {
        return super.getPort(NotificationImplPort, Notification.class, features);
    }

}
